# Test for `AI`
This notebook tests the `conversions` to AI

In [16]:
%load_ext autoreload
import os

module_path = os.path.abspath(os.path.join(".."))

import sys
from pathlib import Path

sys.path.append(str(Path("..").resolve()))

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [17]:
%autoreload 2
from quartopy import Board, Piece, Coloration, Shape, Size, Hole

In [18]:
board = Board("Game Board", False, 4, 4)
board

Game Board:
---- ---- ---- ---- 
---- ---- ---- ---- 
---- ---- ---- ---- 
---- ---- ---- ---- 

In [19]:
%autoreload 2
from quartopy import Board, Piece, Coloration, Shape, Size, Hole
p1 = Piece(1, 4, Size.TALL,  Coloration.BROWN, Shape.CIRCLE,Hole.WITHOUT)
p1
p2 = Piece(1, 4, Size.TALL,  Coloration.BEIGE, Shape.SQUARE,Hole.WITH)
p2

TBQH

In [20]:
board.put_piece(p1, 1, 2)
board.put_piece(p2, 1, 1)
board

Game Board:
---- ---- ---- ---- 
---- TBQH TDCN ---- 
---- ---- ---- ---- 
---- ---- ---- ---- 

In [21]:
b2 = Board("Game Board2", False, 4, 4)
b2.put_piece(p1, 3, 2)
b2

Game Board2:
---- ---- ---- ---- 
---- ---- ---- ---- 
---- ---- ---- ---- 
---- ---- TDCN ---- 

In [22]:
b2.to_matrix()

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 1., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 1., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [23]:
Board.to_matrix_batch([board, b2])

array([[[[0., 0., 0., 0.],
         [0., 1., 1., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 1., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 1., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [24]:
%autoreload 2
from quartopy import Board, Piece, Coloration, Shape, Size, Hole
p1 = Piece(1, 4, Size.TALL, Coloration.BEIGE, Shape.CIRCLE, Hole.WITH)
print(p1)
p2 = Piece(1, 4, Size.TALL, Coloration.BEIGE, Shape.SQUARE, Hole.WITH)
print(p2)
v = p1.vectorize_onehot()
v

TBCH
TBQH
(2, 2, 2, 2)
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 1.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [25]:
p1.vectorize()

array([[1., 0., 0., 1.]])

In [26]:
import numpy as np

i = np.random.randint(0, 16)
w = np.zeros(16)
w[i] = 1
w

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
%autoreload 2
from quartopy import Board, Piece, Coloration, Shape, Size, Hole
p1 = Piece(1, 4, Size.TALL, Coloration.BROWN, Shape.CIRCLE, Hole.WITHOUT)
print(p1)
v = p1.vectorize_onehot()
print(v)
p = Piece.from_onehot(v, [1, 4])
print(p)

for i in range(16):
    pi = Piece.from_index(i, 11)
    print(i, pi)

TDCN
(2, 2, 2, 2)
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[1. 0.]
   [0. 0.]]]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
TDCN
0 SBCN
1 SBCH
2 SBQN
3 SBQH
4 SDCN
5 SDCH
6 SDQN
7 SDQH
8 TBCN
9 TBCH
10 TBQN
11 TBQH
12 TDCN
13 TDCH
14 TDQN
15 TDQH
